### ISSUE TITLE
Invalid public bytes for the given curve

### ISSUE THREAD

**Issue by simon0302010** [biemster/FindMy#57] opened 2024-08-07 18:06 UTC
I just got this error while running request_reports.py on Fedora 40 and Python 3.12.4 and I just can't fix it:
```
pyprovision is not installed, querying http://localhost:6969 for an anisette server
200: 1 reports received.
Traceback (most recent call last):
  File "/home/simon/Dokumente/Find My/FindMy/./request_reports.py", line 89, in <module>
    eph_key = ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP224R1(), data[5:62])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 185, in from_encoded_point
    return backend.load_elliptic_curve_public_bytes(curve, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1120, in load_elliptic_curve_public_bytes
    raise ValueError("Invalid public bytes for the given curve")
ValueError: Invalid public bytes for the given curve
```

**Comment by biemster** [comment] 2024-09-30 07:29
duplicate of #52

**Closed by biemster** 2024-09-30 07:29 UTC
